### ISSUE TITLE
Add an example for useSemanticDateRange

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/fiori-elements-feature-showcase#17]
Hello SAP Fiori Elements Feature Showcase Team,

it would be great if the Showcase can be extended with an example that implements 
[useSemanticDateRange](https://ui5.sap.com/#/topic/fef65d03d01a4b2baca28983a5449cf7).

Thank you in advance.

Best Regards
Gregor

**Comment by schiwekM** [comment]
Hi @gregorwolf,
I am sadly currently quite busy with other tasks - however I will try to have a look in May at the topic. The internal feature showcase of this repo already includes it and in May I will hopefully have a look at updating this repo.

BR,
Marten

**Comment by schiwekM** [comment]
Example is now added
