### ISSUE TITLE
Navigation to CustomObjectPage_childEntities3 doesn't work

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/fiori-elements-feature-showcase#25]
Hello,

I try to use the Navigation to CustomObjectPage_childEntities3 from the elements shown in this table:

![Screenshot 2023-12-20 at 17 31 43](https://github.com/SAP-samples/fiori-elements-feature-showcase/assets/2639535/4dff55d2-e1ff-4b96-bad8-6070bb04d92a)

but when I click on the element I get the attached errors:

[localhost-1703089862153.log](https://github.com/SAP-samples/fiori-elements-feature-showcase/files/13729881/localhost-1703089862153.log)

in the console.

**Comment by schiwekM** [comment]
Hi @gregorwolf,
Could you please check again? I just tested and it should work again.

Thanks & BR

**Comment by gregorwolf** [comment]
I can confirm that it works with the currenly configured SAPUI5 Version 1.127.1.
