### ISSUE TITLE
Application is not running anymore folliwing SAP overrnight  libraries update

### ISSUE THREAD

**Issue by InnaVine** [SAP-samples/fiori-elements-feature-showcase#28]
<img width="865" alt="NewError" src="https://github.com/SAP-samples/fiori-elements-feature-showcase/assets/41966409/20eea99a-bdb9-4a23-bfae-1a02ba6cdd8b">

Hi, this code was working absolutely as described yesterday. 
Overnight, I believe, the SAP lid. changed and now it is impossible to start application. The error is below.
Could you please help?
Thank you very much in advance,
Inna

**Comment by schiwekM** [comment]
Hi.

Could you specify what is not working / did you clear your cache? For me everything is still working with 1.123. Only the custom page had issues, which are now fixed.

BR, Marten

**Comment by InnaVine** [comment]
Hi Marten,
Yes, I did clear the cache and even run the whole app in a private window.
The service was running and tile in FLP too, but the app after clicking on the tile was not starting.
Today I have tried again and everything works now. Thank you very much!!! Inna
