### ISSUE TITLE
App doesn't work anymore

### ISSUE THREAD

**Issue by sammok83** [SAP-samples/fiori-elements-feature-showcase#30]
Hi there,

App doesn't seem to be working anymore when clicking on 'go' button:
![image](https://github.com/SAP-samples/fiori-elements-feature-showcase/assets/10509241/c27f47ee-dea9-4477-ac2c-d4f8559a21ef)

![image](https://github.com/SAP-samples/fiori-elements-feature-showcase/assets/10509241/23a909f0-a4ed-4384-9e78-e8e757445106)

**Comment by schiwekM** [comment]
Hi @sammok83,

I just checked and it worked for me. Could you run 'npm install' and start again with 'cds watch' and check if it is still not running?

Thanks & BR,
Marten

**Comment by sammok83** [comment]
@schiwekM Thanks Marten. Looks like something to be in my cache. Works now
