### ISSUE TITLE
Flexible Column Layout

### ISSUE THREAD

**Issue by grknylmz** [SAP-samples/fiori-elements-feature-showcase#4]
Hi, is it possible to add Flexible Column Layout details to this application also?
I know in the description it says check it with application modeler but it is pretty buggy so maybe it is better to incorporate following guide,

https://sapui5.hana.ondemand.com/#/topic/e762257125b34513b0859faa1610b09e

**Comment by stefan0816** [comment]
Hi Gurkan,
can you try again with the latest version of Fiori tools? I change these things in the Fiori tools page map and it works well for me:
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/35706403/162152980-279372ca-a3d5-4d9b-b201-106cc9ada174.png">
