### ISSUE TITLE
Value help not giving any value from external service

### ISSUE THREAD

**Issue by ahmedkhan29789** [SAP-samples/fiori-elements-feature-showcase#5]
Hi, Marten,

thanks for the amazing repository describing all valuable features,
One of the feature of value help I am trying the same way as you did but the value help is not fetching me any data, Can you please have a look at this https://answers.sap.com/questions/13557571/authorization-error-when-using-external-service-in.html

**Comment by schiwekM** [comment]
Hi @ahmedkhan29789,
I will close the issue, because a working solution was provided here: https://answers.sap.com/questions/13557571/authorization-error-when-using-external-service-in.html
Best regards,
Marten
