### ISSUE TITLE
Navigation within the application

### ISSUE THREAD

**Issue by P2001319958** [SAP-samples/fiori-elements-feature-showcase#6]
Hi Marten,

This is definitely an excellent sample application which incorporates a lot of features of SAP Fiori Elements.  I have referred to the code for a few of my requirements. However, I am trying to achieve something, for which, I am not finding a suitable solution anywhere. You have incorporated navigation to a different application when the user clicks on the IBN button; I am trying to navigate to another Object page within my application when a custom action button on the Object page header is clicked. Would you be able to kindly guide me with an approach for this? Any help is highly appreciated!

**Comment by schiwekM** [comment]
Hi @P2001319958,

You could use the extensionAPI for Fiori Elements V4: https://sapui5.hana.ondemand.com/test-resources/sap/fe/core/fpmExplorer/index.html#/controllerExtensions/controllerExtensionsOverview/routingExtensibility
The only thing you would need to fetch is the bindingContext of the other Object Page.

I hope that helps.

Best regards,
Marten

**Comment by P2001319958** [comment]
Hi Marten,

I would like to update you that it did help!! I was able to get a direction from your response and was able to progress with my application. Thanks a ton for the help, I really appreciate it, not to mention the superfast revert! :-) Really grateful for your help!
And my apologies for the delayed response even though I got your response almost immediately, I was busy implementing the steps. Thanks again and have a great day!! :-)

**Comment by schiwekM** [comment]
Hi Sachin,

happy to hear that. I will close the issue then.
Have a great day too.

Best regards,
Marten

**Comment by P2001319958** [comment]
Hi Marten,

Hope you are doing well!

Sorry to bother you, but you have helped me in the past on this topic and
now I was looking for some expert opinion from you regarding another topic.
I would really appreciate it and be very grateful if you could provide a
solution to my dilemma.

I am currently using a SAP Conversational AI Web Client in one of my
applications. It is positioned at the bottom right corner of the page by
default and as a result overlaps with my existing onscreen buttons (like
"Submit" etc). I can move/reposition the chatbot once I open it to start a
conversation, but that is not a working resolution for obvious reasons.
Would you happen to have any workarounds to reposition the chatbot button
to maybe right-center of the screen (using CSS?)?

Your response would be highly appreciated, thanks in advance and have a
great day! :-)




*Thanks & Regards,Sachin Hegde+91 9900509036*

**Comment by gregorwolf** [comment]
Hi @P2001319958 ,

I think you should post this as a question in the SAP Community.

CU
Gregor

**Comment by P2001319958** [comment]
Hi Gregor,

Sure, I will do that, thank you!




*Thanks & Regards,Sachin Hegde+91 9900509036*

**Comment by schiwekM** [comment]
Hi @P2001319958,

I haven't found the topic in the SAP Community channel, so I will reply here:
Instead of the default button from the SAP Conversational AI Web Client you can use the JavaScript API to open and close the web client (https://help.sap.com/viewer/a4522a393d2b4643812b7caadfe90c18/latest/en-US/87acba124c7a4f0881af1902bf4d69ed.html). 
The API documentation can be found here: https://github.com/SAPConversationalAI/WebClientDevGuide
I am not familiar with your use case, but instead of using a custom action inside the app, you may want to have a look at enhancing the Shell-Bar for your app with the button to trigger your chatbot, as it would be more coherent regarding UX.

Best regards,
Marten
