### ISSUE TITLE
Can't run project

### ISSUE THREAD

**Issue by pylnata** [SAP-samples/fiori-elements-feature-showcase#8]
Hello,

I can't run project locally. In console there are errors:
<img width="1791" alt="Screenshot 2022-05-09 at 10 36 57" src="https://user-images.githubusercontent.com/33361478/167372313-e189c9d8-201f-4ed6-b654-44eb0349047d.png">

Could somebody help?
Thanks

**Comment by gregorwolf** [comment]
I've also discovered some issues with SAPUI5 1.101. Please try with 1.100.

**Comment by gregorwolf** [comment]
You need to replace the occureces of https://ui5.sap.com/ in [app/index.html](https://github.com/SAP-samples/fiori-elements-feature-showcase/blob/main/app/index.html) with https://sapui5.hana.ondemand.com/1.100.2/

**Comment by pylnata** [comment]
@gregorwolf thanks, works now
